<a href="https://colab.research.google.com/github/yash2046/2216101_bootcamp_ml-concepts/blob/main/SMSSPAM_DETECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing library
import pandas as pd
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/SMSSpamCollection',sep='\t',header=None,names=['label','message'])

In [ ]:
data.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
data.shape

(5572, 2)

In [ ]:
#data preprocessing
data['label']=data.label.map({'ham':0,'spam':1})

In [ ]:
data.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

DEMO OF BAG OF WORDS

In [ ]:
documents=['hello , how are you!',
              'win money, win from home ',
              'call me now.',
              'hello, call hello tommorow?']
#apply counvectorizer - import it from sklearn library
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
print(count_vector)

CountVectorizer()


In [ ]:
#fit_transform, transform
count_vector.fit(documents)

CountVectorizer()

In [ ]:
n=count_vector.get_feature_names()
print(n)

['are', 'call', 'from', 'hello', 'home', 'how', 'me', 'money', 'now', 'tommorow', 'win', 'you']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
doc_array=count_vector.transform(documents).toarray()

In [ ]:
doc_array

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0]])

In [ ]:
#converting this array into a dataframe - for understanding
freq_table=pd.DataFrame(data=doc_array,columns=n)

In [ ]:
freq_table

are  call  from  hello  home  how  me  money  now  tommorow  win  you
0    1     0     0      1     0    1   0      0    0         0    0    1
1    0     0     1      0     1    0   0      1    0         0    2    0
2    0     1     0      0     0    0   1      0    1         0    0    0
3    0     1     0      2     0    0   0      0    0         1    0    0

In [ ]:
data.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#load the data
x=data.iloc[:,-1:] # independent --message column
y=data.iloc[:,:-1]

In [ ]:
x


message
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568               Will ü b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [ ]:
y

label
0         0
1         0
2         1
3         0
4         0
...     ...
5567      1
5568      0
5569      0
5570      0
5571      0

[5572 rows x 1 columns]

In [ ]:
#split the data in to training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1,shuffle=True)

In [ ]:
x_train

message
1642  Hi , where are you? We're at  and they're not ...
2899        If you r @ home then come down within 5 min
480   When're you guys getting back? G said you were...
3485  Tell my  bad character which u Dnt lik in me. ...
157                         I'm leaving my house now...
...                                                 ...
905   We're all getting worried over here, derek and...
5192  Oh oh... Den muz change plan liao... Go back h...
3980  CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235   Text & meet someone sexy today. U can find a d...
5157                            K k:) sms chat with me.

[4457 rows x 1 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
#transform the training data into freq vectors and return the matrix
training_data=cv.fit_transform(x_train.values.flatten())

#transform the testing data into freq vectors and return the matrix
testing_data=cv.transform(x_test.values.flatten())

In [ ]:
training_data


<4457x7714 sparse matrix of type '<class 'numpy.int64'>'
	with 59028 stored elements in Compressed Sparse Row format>

In [ ]:
testing_data

<1115x7714 sparse matrix of type '<class 'numpy.int64'>'
	with 14094 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [ ]:
y_test=y_test.values.flatten()
print(y_test)

[0 0 0 ... 0 0 0]


In [ ]:
y_pred=model.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
print("Predicted value for training data:",model.score(training_data,y_train))
print("Training accuracy:",model.score(training_data,y_train)*100)

Predicted value for training data: 0.9923715503702042
Training accuracy: 99.23715503702041


In [ ]:
print("Predicted value for testing data:",model.score(testing_data,y_test))
print("Testing accuracy:",model.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9901345291479821
Testing accuracy: 99.01345291479821


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[965   3]
 [  8 139]]


99.01345291479821

In [ ]:
from sklearn.tree import DecisionTreeClassifier
modeldt=DecisionTreeClassifier()

In [ ]:
modeldt.fit(training_data,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=modeldt.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
print("Predicted value for training data:",modeldt.score(training_data,y_train))
print("Training accuracy:",modeldt.score(training_data,y_train)*100)

Predicted value for training data: 1.0
Training accuracy: 100.0


In [ ]:
print("Predicted value for testing data:",modeldt.score(testing_data,y_test))
print("Testing accuracy:",modeldt.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9739910313901345
Testing accuracy: 97.39910313901345


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[951  17]
 [ 12 135]]


97.39910313901345

In [ ]:
from sklearn.svm import SVC
modelsvc=SVC()

In [ ]:
modelsvc.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [ ]:
y_pred=modelsvc.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
print("Predicted value for training data:",modelsvc.score(training_data,y_train))
print("Training accuracy:",modelsvc.score(training_data,y_train)*100)

Predicted value for training data: 0.9950639443571909
Training accuracy: 99.50639443571909


In [ ]:
print("Predicted value for testing data:",modelsvc.score(testing_data,y_test))
print("Testing accuracy:",modelsvc.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9874439461883409
Testing accuracy: 98.7443946188341


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[967   1]
 [ 13 134]]


98.7443946188341

In [ ]:
from sklearn.ensemble import RandomForestClassifier
modelrf=RandomForestClassifier()

In [ ]:
modelrf.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier()

In [ ]:
y_pred=modelrf.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
print("Predicted value for training data:",modelrf.score(training_data,y_train))
print("Training accuracy:",modelrf.score(training_data,y_train)*100)

Predicted value for training data: 1.0
Training accuracy: 100.0


In [ ]:
print("Predicted value for testing data:",modelrf.score(testing_data,y_test))
print("Testing accuracy:",modelrf.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9829596412556054
Testing accuracy: 98.29596412556054


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[968   0]
 [ 19 128]]


98.29596412556054

In [ ]:
#model     ->  naive_baye    Decision tree       svc        random forest
#accuracy  ->   99              97.2             98.7         98.2